$schema: https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  frontend:
    image: "ghcr.io/sevenc-nanashi/chart_cyanvas/frontend:latest"
    volumes:
      - ./.env.prod:/app/.env

  backend:
    image: "ghcr.io/sevenc-nanashi/chart_cyanvas/backend:latest"
    volumes:
      - ./.env.prod:/app/.env

  sub-audio:
    image: "ghcr.io/sevenc-nanashi/chart_cyanvas/sub-audio:latest"
    restart: always
    volumes:
      - ./.env.prod:/app/.env

  sub-image:
    image: "ghcr.io/sevenc-nanashi/chart_cyanvas/sub-image:latest"
    restart: always
    volumes:
      - ./.env.prod:/app/.env

  sub-sus:
    image: "ghcr.io/sevenc-nanashi/chart_cyanvas/sub-sus:latest"
    restart: always
    volumes:
      - ./.env.prod:/app/.env

  redis:
    image: "redis:7.0.7-alpine"
    restart: always
    volumes:
      - ./data/redis:/data

  postgres:
    image: "postgres:15.1-alpine"
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  nginx:
    image: "nginx:1.23.3-alpine"
    restart: always
    ports:
      - "$FINAL_PORT:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/app/backend-public
