AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

inherit_gem:
  syntax_tree: config/rubocop.yml

Layout/EndOfLine:
  EnforcedStyle: lf

Naming/VariableNumber:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false
