name: "[backend] Lint and Test"

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-*.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get ruby version
        id: ruby-version
        run: |
          echo RUBY_VERSION=$(cat backend/.ruby-version) >> $GITHUB_OUTPUT
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.RUBY_VERSION }}
      # - name: Cache gems
      #   uses: actions/cache@v3
      #   id: cache-gems
      #   with:
      #     path: vendor/bundle
      #     key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-bundler-
      #  FIXME: Fix after https://github.com/actions/runner/issues/449
      - name: Install gems
        if: steps.cache-gems.outputs.cache-hit != 'true'
        working-directory: ./backend
        run: |
          bundle config path vendor/bundle
          bundle config set frozen 'true'
          bundle install --jobs 4 --retry 3

      - name: Run backend lint
        working-directory: ./backend
        run: |
          pwd
          bundle exec rake lint

      - name: Run backend test
        working-directory: ./backend
        run: |
          pwd
          docker compose --env-file ../.env.test --profile test up -d
          cp ../.env.test ../.env
          bundle exec rake parallel:setup
          bundle exec rake parallel:spec

      - name: Dispatch build action
        if: github.ref_name == 'main'
        uses: codex-/return-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          owner: sevenc-nanashi
          repo: chart_cyanvas
          workflow: build.yml
          workflow_timeout_seconds: 120
          workflow_inputs: '{"directory_name": "backend"}'
