name: "[frontend] Lint, Typecheck"

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-*.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.0.0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: frontend/.node-version
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Run frontend lint
        working-directory: ./frontend
        run: |
          cp ../.env.example .env
          pnpm i
          pnpm lint

      - name: Run frontend typecheck
        working-directory: ./frontend
        run: |
          pnpm typecheck

      - name: Cache .next
        uses: actions/cache@v2
        with:
          path: frontend/.next
          key: ${{ runner.os }}-next-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-next-
      - name: Build production
        if: github.ref_name == 'main'
        working-directory: ./frontend
        run: |
          pnpm build

      - name: Build image
        if: github.ref_name == 'main'
        uses: ./.github/actions/build
        with:
          directory-name: frontend
