name: "[sub-sus] Lint, Test, Typecheck"

on:
  push:
    paths:
      - "sub-sus/**"
      - ".github/workflows/sub-sus-*.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.20.0
      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run sub-sus lint
        working-directory: ./sub-sus
        run: |
          pnpm i
          pnpm lint
      - name: Run sub-sus test
        working-directory: ./sub-sus
        run: |
          pnpm test
      - name: Run sub-sus typecheck
        working-directory: ./sub-sus
        run: |
          pnpm typecheck

      - name: Dispatch build action
        if: github.ref_name == 'main'
        uses: codex-/return-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          owner: sevenc-nanashi
          repo: chart_cyanvas
          workflow: build.yml
          workflow_timeout_seconds: 120
          workflow_inputs: '{"directory_name": "sub-sus"}'
