name: "[sub-audio] Lint with clippy"

on:
  push:
    paths:
      - "sub-audio/**"
      - ".github/workflows/sub-audio-*.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: |
            clippy
      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sub-audio lint
        working-directory: ./sub-audio
        run: |
          rustup component add clippy
          cargo clippy
      - name: Dispatch build action
        if: github.ref_name == 'main'
        uses: codex-/return-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          owner: sevenc-nanashi
          repo: chart_cyanvas
          workflow: build.yml
          workflow_timeout_seconds: 120
          workflow_inputs: '{"directory_name": "sub-audio"}'
